[tool.black]
line-length = 79
exclude = ".git,__pycache__,__init__.py,.mypy_cache,.pytest_cache"

[tool.isort]
skip = [".gitignore", ".dockerignore"]
extend_skip = [".md", ".json"]
profile = "black"
line_length = 79
force_grid_wrap = 0
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
ensure_newline_before_comments = true

[tool.interrogate]
exclude = [
    "tests",
    "server/api/",
    "server/models/",
    "server/schemas/",
    "server/__init__.py"
]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = true
ignore-nested-classes = true
ignore-setters = false
fail-under = 0
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 0
quiet = false
whitelist-regex = []
color = true

[tool.pytest.ini_options]
asyncio_mode = "strict"
python_functions = ["test"]
python_files = ["tests/*.py"]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["tests"]
omit = ['*/_version.py', 'versioneer.py', 'setup.py']

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.coverage.html]
title = "Relatório de cobertura"
directory = "templates/coverage"
